"""
Django settings for pantry_manager project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse
from decouple import Config, Csv, RepositoryEnv

try:
    from tzlocal import get_localzone_name
except Exception:  # pragma: no cover - safe fallback when tzlocal is unavailable
    get_localzone_name = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR.parent / '.env'
env = Config(RepositoryEnv(ENV_FILE)) if ENV_FILE.exists() else Config(os.environ)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = env('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


def _build_default_csrf_trusted_origins(hosts):
    origins = []
    for host in hosts:
        host = str(host).strip()
        if not host or host.startswith('.') or '*' in host:
            continue
        if host.startswith('http://') or host.startswith('https://'):
            origins.append(host)
            continue
        if host in ('localhost', '127.0.0.1'):
            origins.append(f'http://{host}')
        else:
            origins.append(f'https://{host}')
    return origins


def _merge_unique_csv(primary, fallback):
    seen = set()
    merged = []

    def _normalize_origin(value):
        parsed = urlparse(value)
        if parsed.scheme and parsed.netloc:
            return f'{parsed.scheme}://{parsed.netloc}'
        return value.rstrip('/')

    for value in [*primary, *fallback]:
        value = str(value).strip()
        if not value or value in seen:
            continue
        value = _normalize_origin(value)
        if not value:
            continue
        if value in seen:
            continue
        seen.add(value)
        merged.append(value)
    return merged


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'inventory',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'inventory.views.custom_exception_handler',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pantry_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.parent.parent / 'Frontend'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pantry_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _clean_env(value):
    if isinstance(value, str):
        return value.strip().strip('"').strip("'")
    return value


def _is_unresolved_template(value):
    return isinstance(value, str) and '${{' in value


def _first_real_env(names, default=''):
    for name in names:
        value = _clean_env(env(name, default=''))
        if value and not _is_unresolved_template(value):
            return value
    return default



DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _first_real_env(['DB_NAME', 'PGDATABASE', 'POSTGRES_DB'], default='pantry_manager'),
            'USER': _first_real_env(['DB_USER', 'PGUSER', 'POSTGRES_USER'], default='postgres'),
            'PASSWORD': _first_real_env(['DB_PASSWORD', 'PGPASSWORD', 'POSTGRES_PASSWORD'], default=''),
            'HOST': _first_real_env(['RAILWAY_TCP_PROXY_DOMAIN', 'DB_HOST', 'PGHOST'], default='localhost'),
            'PORT': _first_real_env(['RAILWAY_TCP_PROXY_PORT', 'DB_PORT', 'PGPORT'], default='5432'),
            'OPTIONS': {
                'sslmode': env('DB_SSLMODE', default='require'),
                'connect_timeout': env('DB_CONNECT_TIMEOUT', default=10, cast=int),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Prefer explicit TIME_ZONE from .env; otherwise use OS local timezone.
if get_localzone_name:
    try:
        _detected_time_zone = get_localzone_name()
    except Exception:
        _detected_time_zone = 'UTC'
else:
    _detected_time_zone = 'UTC'

TIME_ZONE = env('TIME_ZONE', default=_detected_time_zone)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = _merge_unique_csv(
    env(
        'CORS_ALLOWED_ORIGINS',
        default='http://localhost:5173,http://127.0.0.1:5173',
        cast=Csv(),
    ),
    _build_default_csrf_trusted_origins(ALLOWED_HOSTS),
)
CSRF_TRUSTED_ORIGINS = _merge_unique_csv(
    env('CSRF_TRUSTED_ORIGINS', default='', cast=Csv()),
    _build_default_csrf_trusted_origins(ALLOWED_HOSTS),
)

SESSION_COOKIE_SAMESITE = env(
    'SESSION_COOKIE_SAMESITE',
    default='None' if not DEBUG else 'Lax',
)
CSRF_COOKIE_SAMESITE = env(
    'CSRF_COOKIE_SAMESITE',
    default='None' if not DEBUG else 'Lax',
)
SESSION_COOKIE_SECURE = env('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = env('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
SESSION_COOKIE_HTTPONLY = env('SESSION_COOKIE_HTTPONLY', default=True, cast=bool)

SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
